# aqui van todas las configuraciones que se comparten entre produccion y development
# para correr los contenedores en modo development 
# se corré el siguiente comando (sí importa orden de los arcivos en los argumentos)
# docker compose -f docker-compose.yml -f docker-compose-dev.yml up -d --build
# y si se quiere correr en modo de producción se corre el siguiente comando
# docker compose -f docker-compose.yml -f docker-compose-prod.yml up -d --build
services:
  reverse-proxy:
    image: mi-nginx
    container_name: reverse_proxy_subdomain
    build:
      context: ./nginx_docker_files
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./nginx_docker_files/cert/:/usr/share/nginx/cert/
      - ./nginx_docker_files/static-html/:/usr/share/nginx/html/ #esto es un bind mount, ergo la maquinal local puede verlo
#    env_file: 
#      - ./passwords
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true

