services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.123.30-amd64
    #image: docker.n8n.io/n8nio/n8n:latest-amd64
    restart: unless-stopped
    #ports:
      #- "127.0.0.1:5678:5678"
      #- 5678:5678
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      #- N8N_PROTOCOL=https
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      #- WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - WEBHOOK_URL=http://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false #not a problem since we are using a reverse proxy
    volumes:
      #- n8n_data:/home/node/.n8n
      - ./n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
#
#volumes:
#  n8n_data: